### PR TITLE
Use SteamOS's new official support

### PR DESCRIPTION
**Pull request by jeff87218**
Updated to download multiple videos under the /home/deck/.steam/root/config/uioverrides/movies/ directory with their original name.

### CODE REVIEW

**Comment by CapitaineJSparrow** [comment]
Hey there, thanks for the pull request and thanks @denilsonsa for his review ! I'll merge this and do the updates on my end, then update the flatpak repository :)

Cheers

**Comment by CapitaineJSparrow** [comment]
Alright I did some testing after applying all changes, last thing we should have is too ensure `/home/deck/.steam/root/config/uioverrides/movies/` exists, it wasn't the case on my end

**Comment by jeff87218** [comment]
I think issue #12 is solved,and thanks for update review!

**Comment by CapitaineJSparrow** [comment]
Thanks everyone, should be live 

👍https://flathub.org/apps/details/com.steamdeckrepo.manager

**Pull request merged**
